version: '3'

services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Encierra el mapping de puertos en una lista
    environment:
      - PORT=3000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb  # Corregí la variable POSTGRES_USER duplicada a POSTGRES_DB
